{% set version = "0.1.10" %}

package:
  name: caerus
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/caerus/caerus-{{ version }}.tar.gz
  sha256: e2cac5a1f1c5cbdebfa687ccb969a64630510f597724a6590049d1ee79452353
  patches:
    - replace_wget_with_requests.patch  # remove after next release

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - python-wget
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - caerus

about:
  home: https://github.com/erdogant/caerus
  license: MIT
  license_file: LICENSE
  summary: Compute the local-minima with the corresponding local-maxima within the given time-frame.
  doc_url: https://erdogant.github.io/caerus/pages/html/index.html
  dev_url: https://github.com/erdogant/caerus

extra:
  recipe-maintainers:
    - raybellwaves
