{% set version = "1.0.1" %}

package:
  name: caerus
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/caerus/caerus-{{ version }}.tar.gz
  sha256: 193843e50977930569e4070f7d28b1f550df20699b2e048762348d03f0a29f43
  patches:
    - replace_wget_with_requests.patch  # remove after next release

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - caerus

about:
  home: https://github.com/erdogant/caerus
  license: MIT
  license_file: LICENSE
  summary: Compute the local-minima with the corresponding local-maxima within the given time-frame.
  doc_url: https://erdogant.github.io/caerus/pages/html/index.html
  dev_url: https://github.com/erdogant/caerus

extra:
  recipe-maintainers:
    - carlodri
    - raybellwaves
