{% set version = "0.1.9" %}

package:
  name: caerus
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/caerus/caerus-{{ version }}.tar.gz
  sha256: 06b793c4537b663438270ea740c65eafe72d987ad18e942c85bab1bfc6a3a216

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - python-wget
    - tqdm

test:
  imports:
    - caerus

about:
  home: https://github.com/erdogant/caerus
  license: MIT
  license_file: LICENSE
  summary: Compute the local-minima with the corresponding local-maxima within the given time-frame.
  doc_url: https://erdogant.github.io/caerus/pages/html/index.html
  dev_url: https://github.com/erdogant/caerus

extra:
  recipe-maintainers:
    - raybellwaves
