{% set version = "1.0.0" %}

package:
  name: caerus
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/caerus/caerus-{{ version }}.tar.gz
  sha256: 6b8db65b1d27be4472a9e73aa9dc3c19cce9b7e78bfc872633eeebc3ba4d8717

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - python-wget
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - caerus

about:
  home: https://github.com/erdogant/caerus
  license: MIT
  license_file: LICENSE
  summary: Compute the local-minima with the corresponding local-maxima within the given time-frame.
  doc_url: https://erdogant.github.io/caerus/pages/html/index.html
  dev_url: https://github.com/erdogant/caerus

extra:
  recipe-maintainers:
    - raybellwaves
